llista_regals/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path

from llista import views

urlpatterns = i18n_patterns(path("admin/", admin.site.urls), path("", views.index), prefix_default_language=False)

llista/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _


class Category(models.Model):
    name = models.CharField(max_length=256, verbose_name=_("Nom"))
    icon = models.CharField(max_length=2, blank=True, verbose_name=_("Icona (emoticona)"))
    description = models.TextField(blank=True, verbose_name=_("Descripció"))
    priority = models.IntegerField(default=0, verbose_name=_("Prioritat"))

    def __str__(self):
        if self.icon != "":
            return f"{self.icon} {self.name}"
        return self.name

    class Meta:
        ordering = ("-priority", "name")
        verbose_name = _("Categoria")
        verbose_name_plural = _("Categories")


class Product(models.Model):
    name = models.CharField(max_length=256, verbose_name=_("Nom"))
    description = models.TextField(blank=True, verbose_name=_("Descripció"))
    image_url = models.CharField(max_length=256, blank=True, verbose_name=_("Imatge"))
    price = models.DecimalField(max_digits=6, decimal_places=2, blank=True, null=True, verbose_name=_("Preu"))
    url = models.CharField(max_length=256, blank=True, verbose_name=_("Enllaç"))

    needed = models.IntegerField(default=1, verbose_name=_("En necessitem"))
    reserved = models.IntegerField(default=0, verbose_name=_("Reservats"))

    category = models.ForeignKey(to=Category, null=True, on_delete=models.CASCADE, verbose_name=_("Categoria"))

    def __str__(self):
        return self.name

    class Meta:
        ordering = (
            "reserved",
            "name",
        )
        verbose_name = _("Producte")
        verbose_name_plural = _("Productes")

llista/forms.py
from django import forms


class ReserveForm(forms.Form):
    product = forms.IntegerField()

    class Meta:
        widgets = {"product": forms.HiddenInput()}

llista/views.py
from django.contrib import messages
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render

from llista.forms import ReserveForm
from llista.models import Category, Product


def index(request: HttpRequest) -> HttpResponse:
    categories = Category.objects.all()

    if request.method == "POST":
        reserve_form = ReserveForm(request.POST)
        if reserve_form.is_valid():
            product = Product.objects.get(pk=reserve_form.cleaned_data.get("product"))
            if product.reserved >= product.needed:
                messages.error(
                    request=request,
                    message="Aquest producte ja està reservat. "
                    "Prova-ho amb algun altre o torna a carregar la pàgina, sisplau",
                )
            else:
                product.reserved = product.reserved + 1
                product.save()

                messages.success(request=request, message="Enviat correctament, moltes gràcies!")
        else:
            messages.error(
                request=request,
                message="Hi ha hagut algun problema. Torna a intentar-ho més tard o avisa'ns del problema, sisplau",
            )

    form = ReserveForm()

    return render(request, "index.html", {"categories": categories, "form": form})

llista/templates/footer.html
<div class="d-flex justify-content-center text-muted mt-3" style="font-size: 0.8rem">
  <p>
    Alba i Roger {% now "Y" %}
  </p>
</div>

llista/templates/index.html
{% extends "layout.html" %}

{% load bootstrap4 %}
{% load static %}

{% block content %}
  <div class="row">
    <div class="col-12 col-md-4 flex-grow-0">
      <h1>Hola!</h1>
      <p>
        Sóc en Bru Cullell Clotet i vaig néixer el 29 de maig del 2020!
      </p>
      <div class="card colored-border mb-3">
        <div class="row no-gutters">
          <img src="{% static "photo1.jpg" %}" alt="Bru" class="mw-100"/>
        </div>
      </div>
    </div>
    <div class="col-12 col-md-8 flex-grow-0">
      <h1>Què necessito?</h1>

      <p>
        Ja que molts demanàveu a la mama i el papa què necessito, el papa ha fet aquesta web per donar algunes idees de
        coses que creuen que m'agradaran, m'ajudaran a créixer o necessitaré.
      </p>
      <p>
        Tal com estan les coses últimament, als papes els agradaria que tot el que es pugui es compri al comerç local, o
        a petits comerços online. Les joguines, roba i altres coses de la llista són només idees, però si em voleu fer
        més d'un regal que només hi hagi una joguina (sinó no tindré temps de jugar amb tot!).
      </p>
      <p>
        Algunes de les joguines segurament les podreu trobar a:
      </p>
      <ul>
        <li>Girona: Ecològic (C/ Bisbe Lorenzana), La Carpa (Carrer de les Hortes)</li>
        <li>Berga: JugaJoc (C/ Gran Via 78)</li>
      </ul>
      <p>
        Si voleu regalar-me alguna cosa de la llista podeu pitjar el botó perquè els papes es puguin planificar millor.
        Si ho preferiu, els podeu enviar un correu a <a href="mailto:bru.cullell@clotet.dev">bru.cullell@clotet.dev</a>
        o de la manera que hi parleu habitualment (WhatsApp, Telegram, telèfon, etc.).
      </p>
      <p>
        Moltes gràcies!
      </p>

      {% for category in categories %}
        {% if category.product_set.count > 0 %}
          <div class="border-top pt-3 mt-1">
            <h2>
              {% if category.icon %}
                {{ category.icon }}
              {% endif %}
              {{ category.name }}
            </h2>

            {% if category.description %}
              <p>{{ category.description | linebreaks }}</p>
            {% endif %}

            <div class="row row-cols-1 row-cols-md-2">
              {% for product in category.product_set.all %}
                <div class="col-md-6">
                  {% include "product_card.html" %}
                  {% include "reserve_modal.html" %}
                </div>
              {% endfor %}
            </div>
          </div>
        {% endif %}
      {% endfor %}
    </div>
  </div>
{% endblock %}

llista/templates/layout.html
{% load i18n %}
{% load bootstrap4 %}

{% bootstrap_javascript jquery='full' %}

{% load static %}

<!DOCTYPE html>
<html lang="ca">
<head>
  <meta charset="utf-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
  <meta name="description" content="Hola! Sóc en Bru Cullell Clotet i vaig néixer el 29 de maig del 2020!"/>
  <meta name="robots" content="noindex, nofollow"/>

  <!-- FAVICONS -->
  <!-- generic -->
  <link rel="icon" href="{% static "favicon.png" %}" sizes="512x512"/>

  <!-- Android -->
  <link rel="shortcut icon" sizes="196x196" href="{% static "favicon.png" %}"/>

  <!-- iOS -->
  <link rel="apple-touch-icon" href="{% static "favicon.png" %}" sizes="512x512"/>

  <!-- Windows 8 IE 10-->
  <meta name="msapplication-TileColor" content="#FFFFFF"/>
  <meta name="msapplication-TileImage" content="{% static "favicon.png" %}"/>

  <!-- Windows 8.1 + IE11 and above -->
  <meta name="msapplication-config" content="{% static "browserconfig.xml" %}"/>

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootswatch/4.3.1/sketchy/bootstrap.min.css"/>

  <title>Bru</title>

  <style>
    h1, h2, h3, h4, h5, h6 {
      color: #35a8a1;
    }

    h3 a, h3 a:hover {
      text-decoration: none;
      color: inherit;
    }

    .container {
      background: white;
      box-shadow: 0 0 0 5em white;
    }

    .card {
      overflow: hidden;
    }

    .colored-border {
      border-color: #35a8a1;
    }
  </style>
</head>
<body>
<div class="container d-flex flex-column" style="min-height: 100vh;">
  <div class="flex-grow-1 pt-5">
    {% bootstrap_messages %}
    {% block content %}{% endblock %}
  </div>
  {% include 'footer.html' %}
</div>

<script>
  $(function () {
    $('[data-toggle="tooltip"]').tooltip()
  })
</script>
</body>
</html>

llista/templates/product_card.html
{% with needed=product.needed reserved=product.reserved %}
  <div class="card mb-3"{% if reserved >= needed %} title="Reservat"{% endif %}>
    <div class="row no-gutters">
      {% if product.image_url %}
        {% if product.url %}
          <a href="{{ product.url }}" target="_blank" rel="noopener noreferrer">
            <img src="{{ product.image_url }}" class="card-img-top" alt="{{ product.name }}"/>
          </a>
        {% else %}
          <img src="{{ product.image_url }}" class="card-img-top" alt="{{ product.name }}"/>
        {% endif %}
      {% endif %}

      <div class="card-body">
        <h3 class="card-title{% if reserved >= needed %} text-secondary" style="text-decoration: line-through{% endif %}">
          {% if product.url %}
            <a href="{{ product.url }}" target="_blank" rel="noopener noreferrer">
              {{ product.name }}
            </a>
          {% else %}
            {{ product.name }}
          {% endif %}
        </h3>

        <p class="card-text">{{ product.description | linebreaks }}</p>

        <p class="card-text">
          <a href="{{ product.url }}" target="_blank" rel="noopener noreferrer">{{ product.url }}</a>
        </p>

        {% if reserved < needed %}
          {% if product.price %}
            <p class="card-text">{{ product.price }}€</p>
          {% endif %}

          <button class="btn btn-primary btn-block mr-3" data-toggle="modal"
                  data-target="#reserveModal{{ product.id }}">
            T'ho regalarem!
          </button>
        {% endif %}
      </div>
    </div>
  </div>
{% endwith %}

llista/templates/reserve_modal.html
{% load bootstrap4 %}

<div class="modal" id="reserveModal{{ product.id }}" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <form method="post">
      {% csrf_token %}

      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Reservar</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          Segur que vols marcar "{{ product.name }}" com a reservat?

          <input type="hidden" name="product" value="{{ product.id }}"/>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel·lar</button>
          <button type="submit" class="btn btn-primary">Reservar</button>
        </div>
      </div>
    </form>
  </div>
</div>